// ============================================================================
// report/plot_embeds.rs — Embedded SVG file cards (§7)
// ============================================================================

use crate::analysis::report::ReportData;

pub fn build_plot_embeds(data: &ReportData) -> String {
    if data.plot_files.is_empty() {
        return String::new();
    }

    let titles = [
        ("restart_landscape",    "Restart landscape \u{2014} final log-prob per restart"),
        ("convergence_curves",   "Convergence curves \u{2014} loss trace per temp-step"),
        ("annealing_profile",    "Annealing profile \u{2014} loss by temperature step"),
        ("cluster_balance",      "Cluster balance \u{2014} cells per inferred donor"),
        ("posterior_confidence", "Posterior confidence \u{2014} per-cell certainty"),
        ("thread_efficiency",    "Thread efficiency \u{2014} restarts and best log-prob per thread"),
    ];

    let mut html = "\
        <hr class=\"section-divider\"/>\n\
        <div class=\"section-label\">Diagnostic Plots</div>\n\
        <h2>SVG Diagnostic Plots</h2>\n\
        <p class=\"section-desc\">Generated by the Rust plot engine from live run data.</p>\n\
        <div class=\"plots-grid\">\n".to_string();

    for f in &data.plot_files {
        let title = titles.iter()
            .find(|(key, _)| f.contains(key))
            .map(|(_, t)| *t)
            .unwrap_or("Diagnostic plot");
        html += &format!(
            r#"<div class="plot-card">
  <div class="plot-title">{title}</div>
  <img src="{f}" alt="{title}" loading="lazy"/>
</div>
"#
        );
    }
    html += "</div>\n";
    html
}
